// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DiscoveredWorkerDto = { name: string, os: string, arch: string, port: number, version: string, addresses: Array<string>, };
