// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which phase of a build job a [`Message::JobProgress`] update describes.
 */
export type JobPhase = "cloning" | "deps" | "building" | "packaging";
