[package]
name = "worker-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
artifacts = { version = "0.1.0", path = "../../crates/artifacts" }
axum = { version = "0.8.9", features = ["ws"] }
axum-server = { version = "0.8.0", features = ["tls-rustls"] }
dirs = "6.0.0"
discovery = { version = "0.1.0", path = "../../crates/discovery" }
executor = { version = "0.1.0", path = "../../crates/executor" }
protocol = { version = "0.1.0", path = "../../crates/protocol" }
rand = "0.10.2"
rcgen = "0.14.8"
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
futures-util = "0.3.33"
tempfile = "3.27.0"
tokio-tungstenite = "0.30.0"
